e_shop/cart/urls.py
from django.urls import path
from cart import views


app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_details'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
]

e_shop/e_shop/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('e_shopee.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

e_shop/e_shopee/urls.py
from e_shopee import views
from django.urls import path


app_name = 'e_shopee'

urlpatterns = [
    path('', views.all_product_category, name='all_product_category'),
    path('<slug:c_slug>/', views.all_product_category, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.all_product_details, name='product_category_details'),
]

e_shop/search_app/urls.py
from django.urls import path
from search_app import views

app_name = 'search_app'
urlpatterns = [
    path('', views.search_result, name='search_result'),
]

e_shop/cart/models.py
from django.db import models
from e_shopee.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return '{}'.format(self.product)

e_shop/e_shopee/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('e_shopee:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    desc = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    img = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_url(self):
        return reverse('e_shopee:product_category_details ', args=[self.category.slug, self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

e_shop/search_app/models.py
from django.db import models

# Create your models here.

e_shop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from e_shopee.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
            cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()
    return redirect('cart:cart_details')


def cart_details(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_details')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_details')

e_shop/e_shopee/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def all_product_category(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug is not None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    paginator = Paginator(products_list, 12)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        product = paginator.page(page)
    except (EmptyPage, InvalidPage):
        product = paginator.page(paginator.num_pages)
    return render(request, 'category.html', {'category': c_page, 'product': product})


def all_product_details(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product': product})

e_shop/search_app/views.py
from django.shortcuts import render
from e_shopee.models import Product
from django.db.models import Q


def search_result(request):
    product = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        product = Product.objects.all().filter(Q(name__contains=query) | Q(desc__contains=query) | Q(price__contains=query))
    return render(request, 'search.html', {'query': query, 'product': product})

e_shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div>
        {% include 'header.html' %}
        {% include 'nav.html' %}
        {% block content %}
        {% endblock %}
    </div>
        {% include 'footer.html' %}
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

e_shop/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
        THIS IS THE CART PAGE. PROCEED TO REVIEW YOUR ITEMS AND PLACE THE ORDER
{% endblock %}
{% block title %}
    CART - E STORE COMPANY PVT LTD
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title"> YOUR SHOPPING CART EMPTY</h1><br>
        <p>PLEASE CLICK <a href="{% url 'e_shopee:all_product_category' %}"> HERE</a>TO CONTINUE SHOPPING</p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">YOUR SHOPPING CART</h1><br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <table class="table my_custom_table">
            <thead class="my_custom_thead ">
                <tr>
                    <th>
                        YOUR_ITEMS
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for cart_item in cart_items %}
                <tr>
                    <td>
                        <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.img.url}}" alt="" class="float-left rounded custom_image" width="100%" height="100px"></a>
                    </td>
                    <td class="text-left">
                        <b>PRODUCT_NAME:</b>{{cart_item.product.name}}
                        <br>
                        <b>SKU:</b> {{cart_item.product.id}}
                        <br>
                        <b>PRICE: </b> $ {{cart_item.product.price}}
                        <br>
                        <b> QUANTITY: </b> {{cart_item.quantity}} x {{cart_item.product.price}}

                    </td>
                    <td>&nbsp;
                        &nbsp;
                        &nbsp;
                       <b>TOTAL:</b>
                       &nbsp; ${{cart_item.sub_total}}
                    </td>
                    <td>
                        {% if cart_item.quantity < cart_item.product.stock %}
                    </td>
                    <td>
                        <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %} " class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                        {% else %}
                         <td>
                        &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-trash custom_icon"></i></a>
                    </td>
                </tr>
                        {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
                <tr>
                    <th>
                        CHECKOUT
                    </th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    PLEASE REVIEW YOUR SHOPPING CART ITEMS BEFORE PROCEEDING WITH THE ORDER PAYMENT.
                </td>
            </tr>
            <tr>
                <td class="text-left">
                    NET TOTAL : <strong>&nbsp; {{total}}</strong>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="http://127.0.0.1:8000/shop/vegetables/" class="btn btn-outline-success btn-block my_custom_button">VEGETABLE CATEGORY</a>
            <a href="http://127.0.0.1:8000/shop/fruits/" class="btn btn-outline-success btn-block my_custom_button">FRUITS CATEGORY</a>
            <a href="{% url 'e_shopee:all_product_category' %}" class="btn btn-outline-success btn-block my_custom_button">CONTINUE SHOPPING</a>
            <a href="{% url 'e_shopee:all_product_category' %}" class="btn btn-outline-primary btn-block my_custom_button">PROCEED TO PAY </a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

e_shop/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        WELCOME TO E STORE WHERE YOU CAN BUY DIFFERENT PRODUCTS ...
    {% endif %}
{% endblock %} 
{% block title %}
    {% if category %}
        {{category.name}} - E STORE
    {% else %}
        See Our New Collections - E STORE
    {% endif %}
{% endblock %}
{% block content %}
    {% if category %}
    <div>
        <div class="row my_row_class">
            <div class="mx-auto">
                <p><a href="{% url 'e_shopee:all_product_category' %}">| HOME |</a></p>
            </div>
        </div>
    </div>
    {% endif %}
<div class="mx-auto">
    {% if category %}
        <img src="{{category.img.url}}" alt="{{category.name}}" width="1350px">
</div>
    <br>
<div>
    <h1 class="text-center"><b>{{category.name}}</b></h1>
    <p class="text-center">{{category.price}}</p>
</div>
    {% else %}
<div class="my_images my_image_padding">
    <img src="{% static 'img/banner1.png' %}" alt="OUR PRODUCTS" width="1300px">
</div>
    <br>
<div>
    <h1 class="text-center my_title">OUR PRODUCT COLLECTIONS</h1>
    <p class="text-center">Vegetables consist of a large group of plants consumed as food. Perishable when fresh but able to be preserved by a number of processing methods, they are excellent sources of certain minerals and vitamins and are often the main source of dietary fibre. The consumption of vegetables has increased significantly as consumers have become more health-conscious. Owing to the perishable nature of the fresh produce, international trade in vegetables is mostly confined to the processed forms.</p>
</div>
    {% endif %}

<div class="container" >
  <div class="row mx-auto">
      {% for product in product.object_list %}
      <div class="my_bottom_margin col-9 col-sm-12 col-md-2 col-lg-2">
          <div class="card text-center" style="min-width:11rem;">
              <a href="{{Product.get_url}}"><img class="card-img-top my_card_image" src="{{product.img.url}}" alt="{{product.name}}"></a>
                  <div class="card-body text-center">
                      <h5 class="card-title">{{product.name}}</h5>
                      <p class="card-text">{{product.desc}}</p>
                      <p class="card-text">$ {{product.price}}</p>
                      <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-outline-success">ADD TO CART</a>
                  </div>
          </div>
      </div>
      {% endfor %}
  </div>
</div>


<div class="mx-auto">
    {% if product.paginator.num_pages > 1 %}

    <hr>
    <div class="text-center">
        {% for pg in product.paginator.page_range %}
            <a href="?page={{pg}}" class="btn btn-light {% if product.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
    {% endif %}
</div>

{% endblock %}

e_shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center"> &copy; E store pvt ltd. All Rights Reserved</p>
</div>

e_shop/templates/header.html
{% load static %}
<header>
    <a href="{% url 'e_shopee:all_product_category' %}"><img src="{% static 'img/logo1.png' %}" alt="logo image" width="80px" height="70px"></a>
</header>

e_shop/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'e_shopee:all_product_category' %}">HOME</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">E_SHOP</a>
            </li>
            <li class="nav-item">
                <a href="http://127.0.0.1:8000/shop/vegetables/" class="nav-link">VEGETABLES</a>
            </li>
            <li class="nav-item">
                <a href="http://127.0.0.1:8000/shop/fruits/" class="nav-link">FRUITS</a>
            </li>
<!--            <li class="nav-item dropdown {% if 'e_shopee' in request.path %} active {% endif %}">-->
<!--                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--                    CATEGORIES-->
<!--                </a>-->
<!--                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--                    <li><a class="dropdown-item" href="{% url 'e_shopee:all_product_category' %}">ALL PRODUCTS</a></li>-->
<!--                    {% for cart in links %}-->
<!--                    <li><a class="dropdown-item" href="{{cart.get_url}}">{{cart.name}}</a></li>-->
<!--                    {% endfor %}-->
<!--                </ul>-->
<!--            </li>-->
            {% if item_count > 0 %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:cart_details' %}"><i class="fa fa-shopping-cart"></i>( {{item_count}} )</a>
            </li>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:search_result' %}" method="get">
        {% csrf_token %}
            <input class="form-control mr-sm-2" type="search" placeholder="Search"  name="q" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search"></i> </button>
        </form>
    </div>
</nav>

e_shop/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{products.desc|truncatewords:155}}
{% endblock %}
{% block title %}
    {% if category %}
        {{products.name}} - E STORE
    {% endif %}
{% endblock %}
{% block content %}
<div class="row my_prod_row_class">
    <div class="mx-auto">
        <p><a href="{% url 'e_shopee:all_product_category' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | <a href="#"> {{product.name}} </a></p>
    </div>
</div>
<div class="container">
    <br>
    <div class="row">
        <div class="col-12 col-sm-12 col-md-12 col-lg-5 text-center">
            <div style="width:18rem">
                <img src="{{product.img.url}}" alt="{{product.name}}">
            </div>
        </div>
        <div>
            <div class="col-3 col-sm-12 col-md-12 col-lg-8">
                <div>
                    <h1 class="my_prod_title"><b>{{product.name}}</b></h1>
                    <p>$ {{ product.price}}</p>
                    <p class="my_title"><b>ABOUT {{product.name}}</b></p>
                    <p>{{product.desc}}</p>
                    <p><b>CATEGORY :</b> {{product.category}}</p>
                    {% if product.stock <= 0 %}
                    <p class="text-center"><b>OUT OF STOCK</b></p>
                    {% else %}
                    <a class="btn btn-success" href="{% url 'cart:add_cart' product.id %}">ADD TO CART</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

e_shop/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    WE HAVE VARIETY OF PRODUCTS

{% endblock %}
{% block title %}
SEARCH
{% endblock %}
{% block content %}

<div>
    <p class="text-center my_search_text">YOU HAVE SEARCHED FOR : <b>"{{query}}"</b></p>
</div>

<div class="container" >
  <div class="row mx-auto">
      {% for product in product %}
      <div class="my_bottom_margin col-9 col-sm-12 col-md-2 col-lg-2">
          <div class="card text-center" style="min-width:11rem;">
              <a href="{{Product.get_url}}"><img class="card-img-top my_card_image" src="{{product.img.url}}" alt="{{product.name}}"></a>
                  <div class="card-body text-center">
                      <h5 class="card-title">{{product.name}}</h5>
                      <p class="card-text">{{product.desc}}</p>
                      <p class="card-text">$ {{product.price}}</p>
                      <a href="{% url 'cart:add_cart' product.id %}" class="btn btn-outline-success">ADD TO CART</a>
                  </div>
          </div>
      </div>
      {% empty %}
  </div>
</div>
     {% endfor %}
<div class="row mx-auto">
    <p class="text-center my_search_text"> RESULTS FOUND</p>
</div>
{% endblock %}